<?php

use Symfony\Component\HttpFoundation\RedirectResponse;


function newsletter_mailchimp_sularyy_theme($existing, $type, $theme, $path) {
//  \Drupal::service('page_cache_kill_switch')->trigger();
return [
  'newsletter' => [
    'render element' => 'form',
    'variables'=> [
     'form' => NULL,
   ],
 ],
];
}

/*
function newsletter_sularyy_mail($key, &$message, $params) {

  $body =
"Hola, el meu nom és " . $params[nom] . "

Vull subscriure al vostre newsletter el

meu correu: " . $params['email'] . "

Merci";

  $message['subject'] = "Informació cistellas";
  $message['body'][] = Drupal\Core\Mail\MailFormatHelper::htmlToText($body);
}
*/